version: "3.9"

services:
  api:
    build: .
    container_name: fastapi_api
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: fastapi_db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
